apiVersion: v1
kind: ConfigMap
metadata:
  name: obs-mcp-config
  namespace: obs-mcp
data:
  auth-mode: "header"
  toolsets: "metrics,traces,otelcol"
  # this is the default prometheus url for kube-prometheus stack
  prometheus-url: "http://prometheus-k8s.monitoring.svc:9090"
  # this is the default alertmanager url for kube-prometheus stack
  alertmanager-url: "http://alertmanager-main.monitoring.svc:9093"
