name: E2E Setup
description: Common setup for E2E tests

runs:
    using: "composite"
    steps:
        - name: Install Go
          uses: actions/setup-go@v6
          with:
              go-version-file: go.mod
              check-latest: true

        - name: Install Kind
          uses: helm/kind-action@v1.13.0
          with:
              version: v0.30.0
              install_only: true

        - name: Start kind cluster and setup environment
          run: make test-e2e-setup
          shell: bash
